name: macOS Test

on:
  workflow_dispatch:
  pull_request:

jobs:
  perl:

    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4

      - name: Install perlbrew
        run: |
          curl -L https://install.perlbrew.pl | bash

      - name: Build Perl 5.38.4
        run: |
          source ~/perl5/perlbrew/etc/bashrc

          perlbrew install perl-5.38.4

          perlbrew use perl-5.38.4

          perl -V

      - name: Install cpanminus
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew use perl-5.38.4

          perl -MCPAN -e 'install App::cpanminus'

          cpanm --version

      - name: Clone Biodiverse
        run: |
          git clone --branch master --depth=1 \
            https://github.com/shawnlaffan/biodiverse.git

      - name: Install Biodiverse dependencies
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew use perl-5.38.4

          cd biodiverse
          cpanm --installdeps --notest .

      - name: Run Biodiverse tests
        run: |
          source ~/perl5/perlbrew/etc/bashrc
          perlbrew use perl-5.38.4

          cd biodiverse
          prove -j4 -l t
