name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-windows:
    uses: ./.github/workflows/windows-runtime.yml
    with:
      build_type: release

  build-macos:
    uses: ./.github/workflows/macos-runtime.yml
    with:
      build_type: release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Future Linux release build"
