name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-windows:
    uses: ./.github/workflows/windows-runtime.yml
    with:
      build_type: release

  build-macos:
    uses: ./.github/workflows/macos-runtime.yml
    with:
      build_type: release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Future Linux release build"

  update-releases-json:
    needs:
      - build-windows

    runs-on: ubuntu-latest

    steps:
      - run: |
          VERSION="${{ github.ref_name }}"
          WINDOWS_FILENAME="${{ needs.build-windows.outputs.windows_filename }}"
          WINDOWS_SHA256="${{ needs.build-windows.outputs.windows_sha256 }}"

          echo "$VERSION"
          echo "$WINDOWS_FILENAME"
          echo "$WINDOWS_SHA256"
