name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build-windows:
    uses: ./.github/workflows/windows-runtime.yml
    with:
      build_type: release

  build-macos:
    uses: ./.github/workflows/macos-runtime.yml
    with:
      build_type: release

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Future Linux release build"

  update-releases-json:
    needs:
      - build-windows

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Set release version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Update releases.json
        run: |
          python scripts/update_releases_json.py \
            "$VERSION" \
            "https://github.com/biogeospatial/biodiverseR-perl-engine-builder/releases/download/$VERSION/${{ needs.build-windows.outputs.windows_filename }}" \
            "${{ needs.build-windows.outputs.windows_sha256 }}" \
            "" \
            "" \
            "" \
            ""

      - name: Commit releases.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add releases.json

          if ! git diff --cached --quiet; then
            git commit -m "Add runtime release $VERSION to releases.json"

 #           git pull --rebase origin main
            git push
          fi
