name: Windows Runtime

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5
  PERL_CPANM_OPT: -M https://www.cpan.org
  PERL_CPANM_HOME: /Users/runner/_cpanm
  ST: C:\Strawberry538
  SP_PATHS: \Users\runner\perl5\bin;C:\Strawberry538\perl\bin;C:\Strawberry538\perl\site\bin;C:\Strawberry538\c\bin
  CMAKE_BUILD_PARALLEL_LEVEL: 4

jobs:
  perl:

    runs-on: windows-latest
    
    permissions:
      id-token: write
      contents: read
      attestations: write

    steps:
      - uses: actions/checkout@v7

      - name: Install workflow tools
        shell: pwsh
        run: |
          choco install yq -y

      - name: Load runtime configuration
        shell: pwsh
        run: |
          "BD_BRANCH=$(yq -r '.globals.biodiverse.branch' .github/runtime-config.yml)" >> $env:GITHUB_ENV

          "BDR_BRANCH=$(yq -r '.globals.biodiverser.branch' .github/runtime-config.yml)" >> $env:GITHUB_ENV

          "BD_NO_ALIEN_GTKSTACK=$(yq -r '.globals.build.no_alien_gtkstack' .github/runtime-config.yml)" >> $env:GITHUB_ENV

          "SP_URL=$(yq -r '.platforms.windows.strawberry_perl.url' .github/runtime-config.yml)" >> $env:GITHUB_ENV

          "RUNTIME_TEST_PORT=$(yq -r '.globals.runtime.test_port' .github/runtime-config.yml)" >> $env:GITHUB_ENV

      - name: Install Strawberry perl
        run: |
          Invoke-WebRequest -Uri "$env:SP_URL" -OutFile ".\sp.zip"
          Expand-Archive -Path "sp.zip" -DestinationPath "$env:ST"
          ls "$env:ST"
          "PATH=$env:ST\perl\bin;$env:ST\perl\site\bin;$env:ST\c\bin;$env:PATH" >> $env:GITHUB_ENV

      - name: perl -V
        shell: cmd
        run: |
          :: set PATH=%SP_PATHS%;%PATH%
          path
          perl -V
          pwd

        #  These dirs must exist before caching 
        #  is first called or it will not work.
        #  The upload action also does not like dirs with leading dots.
      - name: Make the cache dir
        shell: pwsh
        run: |
          New-Item -Path "$env:PERL_LOCAL_LIB_ROOT" -ItemType Directory
          ls /Users/runner/perl5
          New-Item -Path "$env:PERL_CPANM_HOME" -ItemType Directory
          ls /Users/runner/_cpanm

      - name: Prepare for cache
        shell: cmd
        run: |
          path
          perl -V > perlversion.txt
          ::  change the checksum so we refresh the cache
          echo '20260818' >> perlversion.txt
          
      - name: Cache CPAN modules
        uses: actions/cache@v6
        if: "!cancelled()"
        with:
          path: \Users\runner\perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
            

      #  many of these are already part of the downloaded perl
      - name: Install cpan deps 
        shell: pwsh
        run: |
          echo $env:PATH
          # set PERL_CPANM_HOME=/Users/runner/.cpanm
          perl -E'say $^V'
          cpanm --notest PAR::Packer
          #cpanm App::PP::Autolink
          # cpanm --notest Alien::MSYS
          # cpanm --notest Alien::libtiff
          # cpanm --notest Alien::sqlite
          # cpanm --notest --installdeps Alien::geos::af
          # cpanm --notest -v Alien::geos::af
          # cpanm --notest --installdeps Alien::proj
          # cpanm --notest -v Alien::proj
          # cpanm --notest --installdeps Alien::gdal
          # $env:ALIEN_GDAL_CMAKE_ARGS = "-DGDAL_ENABLE_DRIVER_PDF:BOOL=OFF -DGDAL_USE_CURL=OFF -DBUILD_APPS=OFF"
          # $env:ALIEN_INSTALL_TYPE = "share"
          # cpanm --notest -v Alien::gdal
          cpanm https://github.com/shawnlaffan/biodiverse-utils/releases/download/v1.09/Biodiverse-Utils-1.09.tar.gz
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
          # cpanm --notest Browser::Start
          cpanm --notest ExtUtils::Depends
          cpanm --notest HTTP::Tiny
          cpanm --notest IO::Socket::SSL
          cpanm --notest LWP::Simple
          # cpanm --notest Geo::ShapeFile
          cpanm --notest autovivification
          cpanm --notest Spreadsheet::Read
          cpanm --installdeps --notest Geo::GDAL::FFI
          cpanm Geo::GDAL::FFI

      - name: PAR::Packer with Biodiverse icon
        shell: pwsh
        run: |
          $env:PAR_PACKER = "PAR-Packer-1.064"
          $env:PP_GZ = "$env:PAR_PACKER.tar.gz"
          $env:URL = "https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/$env:PP_GZ"
          echo $env:PATH
          perl -E'say $^V'
          Invoke-WebRequest -Uri $env:URL -OutFile $env:PP_GZ
          tar -xzf $env:PP_GZ
          cd $env:PAR_PACKER
          Copy-Item -Path "..\Biodiverse_icon.ico" -Destination .\myldr\winres\pp.ico
          cpanm --installdeps .
          perl Makefile.PL
          gmake install
          cd ..


      - name: pp-autolink
        shell: pwsh
        run: |
          perl -E'say $^V'
          git clone --depth=1 https://github.com/shawnlaffan/perl-pp-autolink.git
          cd perl-pp-autolink
          perl Makefile.PL
          gmake test 
          gmake install
          cd ..
          where pp_autolink.pl
          # ls /Users/runner/perl5/bin


      - name: Clone biodiverse repo
        shell: pwsh
        run: |
          perl -E'say $^V'
          git clone --branch $env:BD_BRANCH --depth=1 https://github.com/shawnlaffan/biodiverse.git
          cd biodiverse
          cpanm --installdeps .
          #prove t/00-load.t
          #  run all tests
          prove -j4 -l t
          cd ..
          #  add to env
          "PERL5LIB=$env:PERL5LIB;$env:GITHUB_WORKSPACE/biodiverse/lib" >> $env:GITHUB_ENV
          

      - name: Clone BiodiverseR repo
        shell: pwsh
        run: |
          perl -E'say $^V'
          git clone --branch $env:BDR_BRANCH --depth=1 https://github.com/biogeospatial/BiodiverseR.git
          cd BiodiverseR/inst/perl
          cpanm --installdeps .
          $env:PERL5LIB = "$env:PERL5LIB;$env:GITHUB_WORKSPACE/biodiverse/lib"
          echo $env:PERL5LIB
          prove -j4 -l t
          cd ..

      
      - name: Upload cpanm dir
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: cpanm_dir
          path: ${{ env.PERL_CPANM_HOME }}
          include-hidden-files: true

      - name: Upload perl5 dir
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: perl5_dir_win
          path: \Users\runner\perl5
          #include-hidden-files: true

      - name: Build exe
        shell: pwsh
        run: |
          set BD_NO_GUI_DEV_WARN=1
          set BDV_PP_BUILDING=1
          cd BiodiverseR/inst/perl
          where pp_autolink
          echo "$env:PERL_LOCAL_LIB_ROOT/bin/pp_autolink.pl -x -o $env:GITHUB_WORKSPACE/BiodiverseR.exe script/BiodiverseR"
          perl $env:PERL_LOCAL_LIB_ROOT/bin/pp_autolink.pl -x -o $env:GITHUB_WORKSPACE/BiodiverseR.exe script/BiodiverseR
          cd $env:GITHUB_WORKSPACE
          dir
          
      - name: Test BiodiverseR runtime startup
        shell: pwsh
        run: |
          $runtime_url = "http://127.0.0.1:$($env:RUNTIME_TEST_PORT)"
          Write-Host "Runtime URL: $runtime_url"

          Start-Process `
            -FilePath "$env:GITHUB_WORKSPACE\BiodiverseR.exe" `
            -ArgumentList "daemon","-l",$runtime_url `
            -RedirectStandardOutput runtime.out.log `
            -RedirectStandardError runtime.err.log

          Start-Sleep -Seconds 10

          Get-Content runtime.out.log -ErrorAction SilentlyContinue
          Get-Content runtime.err.log -ErrorAction SilentlyContinue

          curl.exe --fail "$runtime_url/api_key"

          Get-Process BiodiverseR -ErrorAction SilentlyContinue |
            Stop-Process -Force


      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Test BiodiverseR runtime installation
        shell: pwsh
        run: |
          Remove-Item `
            "$env:LOCALAPPDATA\BiodiverseR\runtime" `
            -Recurse `
            -Force `
            -ErrorAction SilentlyContinue

          @'
          install.packages(
            "pak",
            repos = "https://cloud.r-project.org"
          )

          pak::pak(
            sprintf(
              "biogeospatial/BiodiverseR@%s",
              Sys.getenv("BDR_BRANCH")
            )
          )

          library(BiodiverseR)

          bd <- BiodiverseR::basedata$new(
            filename = system.file(
              "extdata",
              "example.bds",
              package = "BiodiverseR"
            )
          )

          stopifnot(bd$server_status())

          cat("Runtime installation and startup succeeded\n")
          '@ | Rscript -

      - name: Get build version as SHA of BiodiverseR repo
        id: build_version
        shell: bash
        run: |
          cd BiodiverseR
          v=`git rev-parse --short HEAD`
          echo "BD_VERSION=${v}" >> "$GITHUB_OUTPUT"

        #  need to work out which type is most appropriate
      - uses: actions/attest@v4
        with:
          subject-path: ./Biodiverse*.exe
          predicate-type: 'https://slsa.dev/provenance/v0.2'
          predicate: '{}'
        
      - name: Get release version
        if: inputs.build_type == 'release'
        shell: bash
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

      - name: Package release artifact
        if: inputs.build_type == 'release'
        shell: pwsh
        run: |
          Compress-Archive `
            -Path BiodiverseR.exe `
            -DestinationPath BiodiverseR_win_x64_${env:VERSION}.zip

      - name: Upload release artifact
        if: inputs.build_type == 'release'
        uses: actions/upload-artifact@v7
        with:
          name: BiodiverseR_win_x64_${{ env.VERSION }}
          path: BiodiverseR_win_x64_${{ env.VERSION }}.zip

      - name: Upload release asset
        if: inputs.build_type == 'release'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            BiodiverseR_win_x64_${{ env.VERSION }}.zip

      - name: Upload CI artifact
        if: ${{ inputs.build_type != 'release' }}
        uses: actions/upload-artifact@v7
        with:
          name: BiodiverseR_win_${{ steps.build_version.outputs.BD_VERSION }}
          path: |
            ./Biodiverse*.exe 
